:alembic: Change test.json > testrun.json

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -21,15 +21,15 @@ jobs:
         run: bunx playwright install --with-deps chromium
 
       - name: Tests
-        run: bun run test:ci -- --coverage --coverage.reporter=json --coverage.reporter=json-summary --silent --watch false --reporter=json --reporter=default --outputFile.json=./test.json
+        run: bun run test:ci -- --coverage --coverage.reporter=json --coverage.reporter=json-summary --silent --watch false --reporter=json --reporter=default --outputFile.json=./testrun.json
         continue-on-error: true
         id: tests
 
       - name: Set tests_failed
         run: |
-          echo "tests_failed=$(grep -q 'numFailedTests":0' ./test.json && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
+          echo "tests_failed=$(grep -q 'numFailedTests":0' ./testrun.json && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
 
-      - run: echo ./test.json
+      - run: cat ./testrun.json
 
       - uses: actions/cache@v4
         name: Cache coverage report
