:construction_worker: Simplify "report coverage" step by just having it right after the test run

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -31,12 +31,11 @@ jobs:
         run: |
           echo "coverage_failed=$(grep -q 'ERROR: Coverage' ./stderr.txt && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
 
-      - uses: actions/cache@v4
-        if: success() || failure()
-        name: Cache coverage report
-        with:
-          path: ./coverage
-          key: coverage-${{ github.sha }}
+      - name: Report Coverage
+        # Set if: always() to also generate the report if tests are failing
+        # Only works if you set `reportOnFailure: true` in your vite config as specified above
+        if: ${{ success() || failure() }}
+        uses: davelosert/vitest-coverage-report-action@v2
 
   check-coverage:
     runs-on: ubuntu-latest
@@ -50,29 +49,3 @@ jobs:
         with:
           script: |
             core.setFailed('Coverage failed!')
-
-  report-coverage:
-    runs-on: ubuntu-latest
-    if: ${{ success() || failure() }}
-    needs: [tests]
-
-    permissions:
-      # Required to checkout the code
-      contents: read
-      # Required to put a comment into the pull-request
-      pull-requests: write
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: actions/cache@v4
-        name: Get coverage report
-        with:
-          path: ./coverage
-          key: coverage-${{ github.sha }}
-
-      - name: Report Coverage
-        # Set if: always() to also generate the report if tests are failing
-        # Only works if you set `reportOnFailure: true` in your vite config as specified above
-        if: always()
-        uses: davelosert/vitest-coverage-report-action@v2
